import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import Title from "../components/Title";
import {useUSer} from "../hooks/useUser";

export default function Home({}) {
    useUSer()

    return (
        <div className={styles.container}>
            <Head>
                <title>Bun SH with Next.js</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <Title/>
            </main>
        </div>
    );
}
